# Generated by Django 4.2.6 on 2023-11-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_assigned_to_task_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
    ]
