# Generated by Django 4.2.6 on 2023-11-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High Priority'), ('normal', 'Normal Priority'), ('low', 'Low Priority')], default='normal', max_length=10),
        ),
    ]
